[plan]
builder          = "go"
app_directory    = "/home/ubuntu/ipfs-crawler"
output_directory = "/home/ubuntu/ipfs-crawler/output_data_crawls"
name             = "ipfs-crawler"
version          = "0.1"
command          = "start_crawl"

[aws]
access_key        = "AKIAIPYC7WDA7Z3KM4RA"
secret_key        = "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"
metrics_s3_bucket = "ipfs-crawls2"

    [aws.servers]
    regions            = ["us-east-1", "us-west-1"]
    availability_zones = 2
    instances_per_az   = 1
    instance_type      = "t2.micro"
	ssh_pub_key        = "~/.ssh/terraform.pub"
	ssh_private_key    = "~/.ssh/terraform"

[elasticsearch]
domain   = "https://search-observatory-bn4ftthzrkyzsbnkye5tnoqsbm.eu-west-1.es.amazonaws.com/"
username = "observatory"
password = "$X2EsjBT-D$YB79"
