---
- hosts: probes
  become: true
  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker
    
    - name: Pull Docker image
      docker_image:
        name: vgiotsas/ipfs-crawler:latest
        source: pull
        
    - name: Running the container
      docker_container:
        image: vgiotsas/ipfs-crawler
        name: ipfs-crawler
        state: started
        env:
          AWS_ACCESS_KEY_ID: KEY
          AWS_SECRET_ACCESS_KEY: SECRET
          ES_USER: USERNAME
          ES_PW: PASSWORD
          ES_URL: URL
          bucketname: BUCKET_NAME
          