---
- hosts: probes
  become: true
  tasks:
    - name: check that all default setup actions have finished
      script: /home/ubuntu/p2p-observatory/ansible/check_ready.sh

    - name: Update apt repo and cache
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker
    
    - name: Pull Docker image
      docker_image:
        name: "{{ docker_img }}"
        source: pull
        
    - name: Running the container
      docker_container:
        image: "{{ docker_img }}"
        name: "{{ container_name }}"
        state: started
        env:
          AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
          AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
          bucketname: "{{ bucket_name }}"
          